[package]
name = "NetworkPoolCalculatorReforged"
version = "1.1.0"
edition = "2021"
authors = ["Xanthus58 <xanthus58@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
chrono = "0.4"